export const MEMOS = [
  {
    memoId: 1,
    title: '제목1',
    tags: ['아이1', '아이2'],
    date: '2024-11-23',
    isError: true,
    invisible: true,
    liked: true,
  },
  {
    memoId: 2,
    title: '제목2',
    tags: ['김엄마', '김아빠', '아이1', '아이2'],
    date: '2024-11-23',
    isError: true,
    invisible: true,
    liked: true,
  },
  {
    memoId: 3,
    title: '제목3',
    tags: ['김아빠', '아이1', '아이2'],
    date: '2024-11-23',
    isError: true,
    invisible: true,
    liked: true,
  },
  {
    memoId: 4,
    title: '제목4',
    tags: ['김엄마', '김아빠', '아이1', '아이2'],
    date: '2024-11-23',
    isError: true,
    invisible: true,
    liked: true,
  },
  {
    memoId: 5,
    title: '제목5',
    tags: ['김엄마', '아이1', '아이2'],
    date: '2024-11-23',
    isError: true,
    invisible: true,
    liked: false,
  },
  {
    memoId: 1,
    title: '제목6',
    tags: ['김엄마', '김아빠', '아이2'],
    date: '2024-11-23',
    isError: true,
    invisible: true,
    liked: true,
  },
  {
    memoId: 2,
    title: '제목7',
    tags: ['김엄마', '김아빠', '아이1'],
    date: '2024-11-23',
    isError: true,
    invisible: true,
    liked: true,
  },
  {
    memoId: 3,
    title: '제목8',
    tags: ['아이1', '아이2'],
    date: '2024-11-23',
    isError: true,
    invisible: true,
    liked: true,
  },
  {
    memoId: 4,
    title: '제목9',
    tags: ['김엄마', '김아빠', '아이1', '아이2'],
    date: '2024-11-23',
    isError: false,
    invisible: false,
    liked: true,
  },
  {
    memoId: 5,
    title: '제목10',
    tags: ['김아빠', '아이1', '아이2'],
    date: '2024-11-23',
    isError: false,
    invisible: false,
    liked: true,
  },
  {
    memoId: 1,
    title: '제목11',
    tags: ['김엄마', '김아빠', '아이1', '아이2'],
    date: '2024-11-23',
    isError: false,
    invisible: false,
    liked: false,
  },
  {
    memoId: 2,
    title: '제목12',
    tags: ['김엄마', '아이1', '아이2'],
    date: '2024-11-23',
    isError: false,
    invisible: false,
    liked: true,
  },
  {
    memoId: 3,
    title: '제목13',
    tags: ['김엄마', '김아빠', '아이2'],
    date: '2024-11-23',
    isError: false,
    invisible: false,
    liked: true,
  },
  {
    memoId: 4,
    title: '제목14',
    tags: ['김엄마', '김아빠', '아이1'],
    date: '2024-11-23',
    isError: false,
    invisible: false,
    liked: true,
  },
];
