export const MEMOS = [
  {
    memoId: 1,
    title: '제목1',
    tags: ['아이2'],
    date: '2024-11-23',
    isError: true,
    invisible: true,
    liked: true,
  },
  {
    memoId: 2,
    title: '제목2',
    tags: ['엄마', '아빠', '아이2'],
    date: '2024-11-23',
    isError: true,
    invisible: true,
    liked: true,
  },
  {
    memoId: 3,
    title: '제목3',
    tags: ['아빠', '아이2'],
    date: '2024-11-23',
    isError: true,
    invisible: true,
    liked: true,
  },
  {
    memoId: 4,
    title: '제목4',
    tags: ['엄마', '아빠', '아이2'],
    date: '2024-11-23',
    isError: true,
    invisible: true,
    liked: true,
  },
  {
    memoId: 5,
    title: '제목5',
    tags: ['엄마', '아이2'],
    date: '2024-11-23',
    isError: true,
    invisible: true,
    liked: false,
  },
  {
    memoId: 6,
    title: '제목6',
    tags: ['엄마', '아빠', '아이2'],
    date: '2024-11-23',
    isError: true,
    invisible: true,
    liked: true,
  },
  {
    memoId: 7,
    title: '제목7',
    tags: ['엄마', '아빠'],
    date: '2024-11-23',
    isError: true,
    invisible: true,
    liked: true,
  },
  {
    memoId: 8,
    title: '제목8',
    tags: ['아이2'],
    date: '2024-11-23',
    isError: true,
    invisible: true,
    liked: true,
  },
  {
    memoId: 9,
    title: '제목9',
    tags: ['엄마', '할머니', '아이1', '아이2'],
    date: '2024-11-23',
    isError: false,
    invisible: false,
    liked: true,
  },
  {
    memoId: 10,
    title: '제목10',
    tags: ['아빠', '할머니', '아이2'],
    date: '2024-11-23',
    isError: false,
    invisible: false,
    liked: true,
  },
  {
    memoId: 11,
    title: '제목11',
    tags: ['엄마', '아빠', '아이1', '할아버지'],
    date: '2024-11-23',
    isError: false,
    invisible: false,
    liked: false,
  },
  {
    memoId: 12,
    title: '제목12',
    tags: ['엄마', '아이1', '할아버지'],
    date: '2024-11-23',
    isError: false,
    invisible: false,
    liked: true,
  },
  {
    memoId: 13,
    title: '제목13',
    tags: ['엄마', '아빠', '할아버지'],
    date: '2024-11-23',
    isError: false,
    invisible: false,
    liked: true,
  },
  {
    memoId: 14,
    title: '제목14',
    tags: ['할아버지', '아빠', '아이1'],
    date: '2024-11-23',
    isError: false,
    invisible: false,
    liked: true,
  },
];
